howmuch/about/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.about.views',

	    url(r'^privacy/$', 'privacy', name='privacy'),  
	    url(r'^terms/$', 'terms', name='terms'),
	    url(r'^faq/$', 'faq', name='faq'),
	    url(r'^contact/$', 'contact', name='contact'),

) 

howmuch/home/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.home.views',
        url(r'^$','home', name = "homepage"),
) 

howmuch/pays/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.pays.views',

	    url(r'^test/$', 'paypal', name = 'test paypal'),
)

howmuch/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout
from django.contrib import admin

from howmuch.tags.functions import tags_json

admin.autodiscover()

urlpatterns = patterns('django.views.generic.simple',
    url(r'^', include('howmuch.home.urls')),

    url(r'^login/$',  login),
    url(r'^logout/$', logout, {'next_page' : '/'}),

    url(r'^test/$', 'direct_to_template', {'template': 'test.html'}),
    url(r'^tour/$', 'direct_to_template', {'template': 'tour.html'}),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^facebook/', include('django_facebook.urls')),

    
    url(r'^about/', include('howmuch.about.urls')),
    url(r'^account/', include('howmuch.account.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^article/', include('howmuch.article.urls')),
    url(r'^comments/', include('howmuch.comments.urls')),
    url(r'^config/', include('howmuch.config.urls')),
    url(r'^invoice/', include('howmuch.invoice.urls')),
    url(r'^messages/', include('howmuch.messages.urls')),
    url(r'^notifications/', include('howmuch.notifications.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^pays/', include('howmuch.pays.urls')),
    url(r'^prestige/', include('howmuch.prestige.urls')),
    url(r'^problems/', include('howmuch.problems.urls')),
    url(r'^profile/', include('howmuch.profile.urls')),
    url(r'^search/', include('howmuch.search.urls')),
    url(r'^tags/$', tags_json),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

howmuch/category/models.py
from django.db import models

from howmuch.tags.models import Tag

class Category(models.Model):
	name = models.CharField(max_length=25)
	subname = models.CharField(max_length=35, blank=True, null=True )
	tags = models.ManyToManyField(Tag)

	def __unicode__(self):
		return u'%s' % (self.name)

howmuch/comments/models.py
from django.db import models
from django.contrib.auth.models import User

from howmuch.utils import get_timestamp

class Comment(models.Model):
	owner = models.ForeignKey(User, related_name="owner by comment")
	date = models.DateTimeField(auto_now_add=True)
	comment = models.CharField(max_length=255)

	def __unicode__(self):
		return u'%s' % (self.comment)

	def get_timestamp(self):
		return get_timestamp(self.date)

howmuch/config/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Notifications(models.Model):
    user = models.OneToOneField(User)
    new_offer = models.BooleanField(default=True)
    new_sale = models.BooleanField(default=True)
    new_message = models.BooleanField(default=True)
    confirm_pay = models.BooleanField(default=True)
    confirm_delivery = models.BooleanField(default=True)
    new_critique = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % (self.user)

    """
    Cuando se crea el nuevo usuario tambien se crea su configuracion de notificaciones
    """
    def create_user_config(sender, instance, created, **kwargs):
        if created:
            Notifications.objects.create(user=instance)

    post_save.connect(create_user_config, sender=User)

howmuch/invoice/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from howmuch.article.models import Assignment

class Charge(models.Model):
	owner = models.ForeignKey(User)
	period = models.IntegerField()
	assignment = models.OneToOneField(Assignment)
	date = models.DateField(auto_now_add=True)
	price =  models.IntegerField()
	commission = models.IntegerField(default=0)

	def __unicode__(self):
		return u'%s' % (self.assignment.article.title)

class Invoice(models.Model):
	owner = models.ForeignKey(User)
	invoice = models.CharField(max_length=10)
	period = models.IntegerField(default=1)
	reference = models.CharField(max_length=15, blank=True)
	charges = models.ManyToManyField(Charge)
	total = models.IntegerField(default=0)
	is_paid = models.BooleanField(default=False)
	due_date = models.DateField(blank=True, null=True)

	def __unicode__(self):
		return u'%s' % (self.reference)

	def create_user_invoice(sender, instance, created, **kwargs):
		from howmuch.invoice.functions import generate_reference, generate_number_invoice
		if created:
			invoice = Invoice.objects.create(owner=instance)
			invoice.reference = generate_reference(instance)
			invoice.invoice = generate_number_invoice(invoice.pk)
			invoice.save()


	def get_item_name(self):
		return 'Pago de Factura %s' % (self.invoice)


	post_save.connect(create_user_invoice, sender=User)


class Pay(models.Model):
	from paypal.standard.ipn.models import PayPalIPN

	owner = models.ForeignKey(User)
	date = models.DateTimeField(auto_now_add=True)
	invoice = models.OneToOneField(Invoice)
	amount = models.FloatField()
	reference = models.CharField(max_length=15)

	def __unicode__(self):
		return u'%s' % (self.invoice)

	def create_pay(sender, instance, created, **kwargs):
		from howmuch.invoice.models import Invoice
		from howmuch.invoice.functions import change_status_invoice, generate_invoice, unlock_account

		if created:
			invoice = Invoice.objects.get(invoice=str(instance.invoice))
			pay = Pay.objects.create(owner=invoice.owner, invoice=invoice, amount=float(instance.payment_gross), reference=invoice.reference)
			#Se cambia el status del Invoice
			change_status_invoice(invoice)
			#Se genera una nueva factura
			generate_invoice(invoice.owner)
			#unlock account
			unlock_account(invoice.owner)

	post_save.connect(create_pay, sender=PayPalIPN)

howmuch/pays/models.py
from django.db import models

# Create your models here.

howmuch/profile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

from django_facebook.models import FacebookProfileModel

from howmuch.pictures.models import make_upload_path
from howmuch.settings import PRESTIGE_TYPES

PHONE_CHOICES =(

    ('Casa','Casa'),
    ('Trabajo','Trabajo'),
    ('Celular', 'Celular'),

    )

class Address(models.Model):
    owner = models.ForeignKey(User)
    street = models.CharField(max_length = 100)
    number = models.CharField(max_length = 10)
    suburb = models.CharField(max_length = 100)
    city = models.CharField(max_length = 33)
    state = models.CharField(max_length = 33)
    country = models.CharField(max_length = 33)
    zipcode = models.IntegerField()

    def __unicode__(self):
        return u'%s %s %s %s %s %s %s' % (self.street, self.number, self.suburb, self.city, 
            self.state, self.country, self.zipcode)

    def get_address(self):
        return 'Calle %s, Numero %s, Colonia %s, %s, %s, %s, C.P %s' % (self.street, self.number, self.suburb, 
            self.city, self.state, self.country, self.zipcode)

class Phone(models.Model):
    owner = models.ForeignKey(User)
    place = models.CharField(max_length=20,choices=PHONE_CHOICES)
    number = models.BigIntegerField()

    def __unicode__(self):
        return u'%s' % (self.number)

class AccountBank(models.Model):
    owner = models.ForeignKey(User)
    bank = models.CharField(max_length=20)
    account = models.CharField(max_length=33)

    def __unicode__(self):
        return u'%s %s' % (self.bank, self.account)

class Profile(FacebookProfileModel):
    from howmuch.article.models import Article

    user = models.OneToOneField(User)
    profile_picture = models.ImageField(upload_to=make_upload_path, default = '/media/img/cuantoo_profile_picture.png')
    company = models.CharField(max_length=77, null = True, blank=True)
    is_new = models.BooleanField(default=True)
    is_his_first_post = models.BooleanField(default=True)
    following = models.ManyToManyField(Article, blank = True)
    addresses = models.ManyToManyField(Address, blank = True)
    phones = models.ManyToManyField(Phone, blank = True)
    banks = models.ManyToManyField(AccountBank, blank = True)
    total_purchases = models.IntegerField(default = 0)
    total_sales = models.IntegerField(default = 0)
    prestige = models.CharField(max_length=15, default = PRESTIGE_TYPES['PRESTIGE1']['NAME'])
    positive_points = models.IntegerField(default=0)
    negative_points = models.IntegerField(default=0)
    unread_notifications = models.IntegerField(default = 0)
    unread_conversations = models.IntegerField(default = 0)
    current_invoice = models.IntegerField(default = 1)
    credit_limit = models.IntegerField(default=PRESTIGE_TYPES['PRESTIGE1']['LIMIT'])
    is_block = models.BooleanField(default=False)


    def __unicode__(self):
        return u'%s' % (self.user)

    #Se crea el perfil del usuario en el momento que se crea al usuario
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    post_save.connect(create_user_profile, sender=User)

    def add_unread_notification(self):
        self.unread_notifications += 1
        self.save()

    def remove_unread_notification(self):
        self.unread_notifications -= 1
        self.save()

    def add_unread_conversation(self):
        self.unread_conversations += 1
        self.save()

    def remove_unread_conversation(self):
        self.unread_conversations -= 1
        self.save()

    def add_purchases(self):
        self.total_purchases += 1
        self.save()

    def add_sales(self):
        self.total_sales += 1
        self.save()

    def get_profile_picture(self):
        return str(self.profile_picture.url).split("?")[0]


    def get_banks(self):
        banks = ''
        for bank in self.banks.all():
            banks += 'Banco: %s, Cta: %s. ' % (bank.bank, bank.account)
        return str(banks)

    #Return total points 
    def total_points(self):
        return self.positive_points - self.negative_points

    #Return current invoice of user
    def get_current_invoice(self):
        from howmuch.invoice.models import Invoice

        current_invoice = Invoice.objects.get(owner=self.user, 
            period=self.current_invoice)
        return current_invoice

    #Return progress profile 
    def get_profile_progress(self):
        progress = 25
        if self.addresses.exists():
            progress += 25
        if self.phones.exists():
            progress += 25
        if self.banks.exists():
            progress +=25
        return progress

howmuch/tags/models.py
from django.db import models

class Tag(models.Model):
	name = models.CharField(max_length=50)
	usage = models.IntegerField(default=1)

	def __unicode__(self):
		return u'%s' % (self.name)

howmuch/article/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, Select

from howmuch.article.models import Article, Assignment

QUANTITY_CHOICES = (
    (1,'UNO'),
    (2,'ENTRE 2 y 5'),
    (5,'ENTRE 5 y 10'),
    (10,'MAS DE 10'),
    )

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        exclude = ('owner','tags','date','pictures','title_url', 'comments', 'followers', 'is_active')
        widgets = {
        'price' : TextInput(attrs = {'class' : 'text width-100'}),
        'title' : TextInput(attrs = {'class' : 'text width-100'}),
        'description' : Textarea(attrs = {'class' : 'width-100', 'style':'height:10em'}),
        'quantity' : Select(attrs = {'class' : 'width-100'}),
        'category' : Select(attrs = {'class' : 'width-100'}),
        'state' : Select(attrs = {'class' : 'width-100'}),
        }

class OfferForm(forms.Form):
    quantity = forms.ChoiceField(
        widget = forms.Select(attrs = {'class' : 'width-100'}),
        choices = QUANTITY_CHOICES)
    cprice = forms.IntegerField(
        widget = forms.TextInput(attrs = {'class' : 'text width-100'}))
    message = forms.CharField(
        widget = forms.Textarea(attrs = {'class' : 'width-100', 'style':'height:10em'}))
    picture1 = forms.ImageField(
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image1')"}))
    picture2 = forms.ImageField(required=False,
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image2')"}))
    picture3 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image3')"}))
    picture4 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image4')"}))
    picture5 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image5')"}))

class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        exclude = ('owner', 'article', 'date', 'status', )

howmuch/comments/forms.py
from django.forms import ModelForm

from howmuch.comments.models import Comment

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		exclude = ('owner', 'date', )

howmuch/config/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext, ugettext_lazy as _


from howmuch.config.models import Notifications

class NotificationsConfigForm(ModelForm):
    class Meta:
        model = Notifications
        exclude = {'user',}


class EmailChangeForm(forms.Form):
	"""
	Formulario que le permite al usuario cambiar su correo electronico
	si coincide su password
	"""

	error_messages = {
		'incorrect_password' : _("The Password is incorrect")
	}

	new_email = forms.EmailField(label=_("new email"),
								widget=forms.TextInput(
									attrs={'class':'span12'}))
	password = forms.CharField(label=_("current password"),
								widget=forms.PasswordInput(
									attrs={'class':'span12'}))

	def __init__(self,user,*args,**kwargs):
		self.user = user
		super(EmailChangeForm, self).__init__(*args, **kwargs)

	def clean_password(self):
		if not self.user.check_password(self.cleaned_data['password']):
			raise forms.ValidationError(
				self.error_messages['incorrect_password'])


	def save(self, commit=True):
		self.user.check_password(self.cleaned_data['password'])
		if commit:
			self.user.email = self.cleaned_data['new_email']
			self.user.save()
		return self.user

howmuch/invoice/forms.py
from django import forms 
from django.forms import ModelForm

from howmuch.invoice.models import Pay

class PayForm(ModelForm):
	class Meta:
		model = Pay
		exclude = ('owner', 'date', 'invoice')

howmuch/messages/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from howmuch.messages.models import Message 

class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('owner', 'date', 'conversation')
        widgets = {
            'message' : Textarea(attrs={'class' : 'span6', 'rows' : 2,'placeholder' : 'Escribe un mensaje aqui...'}),
        }

howmuch/pictures/forms.py
from django import forms
from django.forms import ModelForm

from howmuch.pictures.models import Picture

class PictureForm(ModelForm):
    class Meta:
        model = Picture
        exclude = ('owner' , 'date', )

howmuch/prestige/forms.py
from django import forms
from django.forms import ModelForm, Textarea, ClearableFileInput, TextInput, Select

from howmuch.prestige.models import ConfirmPay, ConfirmDelivery, Critique


class ConfirmPayForm(ModelForm):
    class Meta:
        model = ConfirmPay
        exclude = ('owner' , 'assignment', 'date',)
        widgets = {
        'amount' : TextInput(attrs={'class':'width-100'}),
        'message' : Textarea(attrs={'class':'width-100','style':'height:10em'}),
        'picture' : ClearableFileInput(attrs={'class':'text password width-100'}),
        }

class ConfirmDeliveryForm(ModelForm):
    class Meta:
        model = ConfirmDelivery
        exclude = ('owner', 'assignment', 'date',)
        widgets = {
        'message' : Textarea(attrs={'id':'confirm-delivery-file-upload-input','class':'width-100','style':'height:10em'}),
        'picture' : ClearableFileInput(attrs={'class':'text password width-100'}),
        }

class CritiqueForm(ModelForm):
    class Meta:
        model = Critique
        exclude = ('de', 'to', 'assignment', 'date',)
        widgets = {
        'critique' : Select(attrs={'class':'width-30'}),
        'message' : Textarea(attrs={'class':'width-100','style':'height:10em'}),
        }

howmuch/templates/profile/edit.html
{% extends "3columns.html" %}

{% block title %}{% endblock %}

{% block media %}
{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Perfil de usuario</h1>
							<div class="description">
								Aquí puedes cambiar los datos de tu perfil.
							</div>
						</div>
					</div>
					
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if user.profile.get_profile_progress < 100 %}
						<div class="notification border borders margin-bottom-1em text-align-left">
							<div class="strong">Perfil Incompleto</div>
							<div class="notification-info">
								Completalo agregando tu imagen de perfil, direcciones y teléfonos. <a href="#">¿Porque proporciono esta informacion?</a>.
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area width-60 div-center-fix">
							<div class="text-align-left">
								
								<div class="big-user-name margin-1em text-align-center">
									<span class="font-size-1_5em strong">{{ user.get_full_name }}</span>
								</div>
								
								<div class="text-align-center">
									<img class="width-50 border padding-0_5em" src="{{ user.profile.get_profile_picture }}" />
								</div>
								
								<!-- DIVISION --><hr/>
								
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Nombre de la empresa</label>
									{{ form.company }}
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em">
										Introducir en caso de que representes a una empresa.
									</div>
									{% if form.company.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										Favor de introducir correctamente.
									</div>
									{% endif %}
								</div>
								
								<!-- DIVISION --><hr/>
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Subir imagen de perfil</label>
									{{ form.profile_picture }}
									<input id="file-upload-button" type="" class="button green" value="Seleccionar archivo" style="margin:0.5em 0px" />
									
									<script>
										$(window).on('load', function () {
											$('#id_profile_picture').hide();
											$('#file-upload-button').on('click', function () {
												$('#id_profile_picture').click();
											});
										});
									</script>
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em">
										Archivo tipo .jpg, .gif, .bmp o .png
									</div>
									{% if form.profile_picture.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										Verificar archivo
									</div>
									{% endif %}
								</div>
								
								
								<!-- DIVISION --><hr/>
								
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button red width-50" value="Registro" />
								</div>
								
							</div>
						</div>
						<!-- FORM LOGIN ENDS -->
						<br/>
					</form>
					<!-- FORM ENDS -->
					
					<!-- STARTS AREA -->
					<div class="border margin-top-1em padding-1em">
						<div class="title font-size-1_5em">Direcciones</div>
						<div class="notification border borders margin-bottom-1em text-align-left">
							<div class="notification-info">
								<a href="#">¿Para qué agrego ésta información?</a>
							</div>
							</div>
							{% for address in user.profile.addresses.all %}
							<!-- IF INFORMATION -->
							<div class="info-enum border dashed margin-bottom-1em">
								<div class="container padding-1em">
									<div>{{ address.street }}</div>
									<div>{{ address.city }}</div>
									<div>{{ addreess.state }}</div>
								</div>
							</div>
							<!-- ENDIF -->
							{% empty %}
								<div class="strong">No hay direcciones guardadas.
								</div>
							{% endfor %}
							<div>
								<a class="attention" href="/profile/e/newaddress">+ Agregar dirección</a>
							</div>
					</div>
					<!-- ENDS AREA -->
					<!-- STARTS AREA -->
					<div class="border margin-top-1em padding-1em">
						<div class="title font-size-1_5em">Teléfonos</div>
						<div class="notification border borders margin-bottom-1em text-align-left">
							<div class="notification-info">
									<a href="#">¿Para qué agrego ésta información?</a>
							</div>
							</div>
							{% for phone in user.profile.phones.all %}
							<!-- IF INFORMATION -->
							<div class="info-enum border dashed margin-bottom-1em">
								<div class="container padding-1em">
									<div>Teléfono <span class="strong">{{ phone.place }}</span>
									</div>
									<div>{{ phone.number }}</div>
								</div>
							</div>
							<!-- ENDIF -->
							{% empty %}
							<div class="strong">No hay teléfonos guardados.
							</div>
							{% endfor %}
							<div>
								<a class="attention" href="/profile/e/newphone">+ Agregar teléfono</a>
							</div>
					</div>
					<!-- ENDS AREA -->
					<!-- STARTS AREA -->
					<div class="border margin-top-1em padding-1em">
						<div class="title font-size-1_5em">Cuentas bancarias</div>
						<div class="notification border borders margin-bottom-1em text-align-left">
							<div class="notification-info">
								<a href="#">¿Para qué agrego ésta información?</a>
							</div>
							</div>
							{% for bank in user.profile.banks.all %}
							<!-- IF INFORMATION -->
							<div class="info-enum border dashed margin-bottom-1em">
								<div class="container padding-1em">
									<div>Banco <span class="strong">{{ bank.bank }}</span>
									</div>
									<div>{{ bank.account }}</div>
								</div>
							</div>
							<!-- ENDIF -->
							{% empty %}
							<div class="strong">No hay cuentas bancarias guardadas.
							</div>
							{% endfor %}
							<div>
								<a class="attention" href="/profile/e/newaccountbank/">+ Agregar cuenta bancaria</a>
							</div>
					</div>
					<!-- ENDS AREA -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html" %}
{% endblock %}

howmuch/templates/profile/following.html
{% extends "3columns.html" %}

{% block search-bar %}
	{% include "search.html" %}
{% endblock %}

{% block section1 %}
{% endblock %}

{% block section2 %}

<section>
	{% for article in following %}
	<div class="row-fluid wrapper-div hover1">
		<div class="thumbnail span2">
			<img src="{{ MEDIA_URL }}img/cuantoo_profile_picture.png">
		</div>
		<div class="span4">
			<p>
				<a href="{{ article.get_url }}">{{ article.title }}</a>
			</p>
		</div>
		<div>
			<h2>
				${{ article.price }}
			</h2>
		</div>
		<div>
		<!-- Activo o inactivo?-->
		</div>
	</div>
	{% empty%}
	<h4>Aun no estas siguiendo ningun articulo, hazlo ahora</h4>
	{% endfor %}
</section>
{% endblock %}

howmuch/templates/profile/newAccountBank.html
{% extends "3columns.html" %}

{% block title %}Agregar una Cuenta Bancaria{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Agrega una cuenta Bancaria</h1>
							<div class="description">
								Agrega una cuenta Bancaria
							</div>
						</div>
					</div>
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if form.errors %}
						<div class="notification error border borders margin-bottom-1em text-align-left">
							<div class="strong">Error en la forma</div>
							<div class="notification-info">
								Información adicional acerca del error de la forma.
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area div-center-fix">
							<div class="text-align-left">
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Nombre del Banco</label>
									{{ form.bank }}
									<div class="slide-down font-size-0_9em">
										Información adicional del campo.
									</div>
									{% if form.bank.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.bank.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->

								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Numero de Cuenta</label>
									{{ form.account }}
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em">
										Información adicional del campo.
									</div>
									{% if form.account.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.account.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
																
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button green width-50" value="Guardar" />
								</div>
								
							</div>
						</div>
						<!-- FORM LOGIN ENDS -->
						<br/>
					</form>
					<!-- FORM ENDS -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html" %}
{% endblock %}

howmuch/templates/profile/newPhone.html
{% extends "3columns.html" %}

{% block title %}Agregar un Numero Telefonico{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Agrega un Numero Telefonico</h1>
							<div class="description">
								Agrega un Numero Telefonico
							</div>
						</div>
					</div>
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if form.errors %}
						<div class="notification error border borders margin-bottom-1em text-align-left">
							<div class="strong">Error en la forma</div>
							<div class="notification-info">
								Información adicional acerca del error de la forma.
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area div-center-fix">
							<div class="text-align-left">
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Tipo de Telefono</label>
									{{ form.place }}
									<div class="slide-down font-size-0_9em">
										Información adicional del campo.
									</div>
									{% if form.place.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.place.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->

								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">Numero Telefonico</label>
									{{ form.number }}
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em">
										Información adicional del campo.
									</div>
									{% if form.number.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.number.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
																
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button green width-50" value="Guardar" />
								</div>
								
							</div>
						</div>
						<!-- FORM LOGIN ENDS -->
						<br/>
					</form>
					<!-- FORM ENDS -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html" %}
{% endblock %}