howmuch/about/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.about.views',

	    url(r'^privacy/$', 'privacy', name='privacy'),  
	    url(r'^terms/$', 'terms', name='terms'),
	    url(r'^faq/$', 'faq', name='faq'),
	    url(r'^contact/$', 'contact', name='contact'),

) 

howmuch/home/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.home.views',
        url(r'^$','home', name = "homepage"),
) 

howmuch/pays/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('howmuch.pays.views',

	    url(r'^test/$', 'paypal', name = 'test paypal'),
)

howmuch/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout
from django.contrib import admin

from howmuch.tags.functions import tags_json

admin.autodiscover()

urlpatterns = patterns('django.views.generic.simple',
    url(r'^', include('howmuch.home.urls')),

    url(r'^login/$',  login),
    url(r'^logout/$', logout, {'next_page' : '/'}),

    url(r'^test/$', 'direct_to_template', {'template': 'test.html'}),
    url(r'^tour/$', 'direct_to_template', {'template': 'tour.html'}),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^facebook/', include('django_facebook.urls')),

    
    url(r'^about/', include('howmuch.about.urls')),
    url(r'^account/', include('howmuch.account.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^article/', include('howmuch.article.urls')),
    url(r'^comments/', include('howmuch.comments.urls')),
    url(r'^config/', include('howmuch.config.urls')),
    url(r'^invoice/', include('howmuch.invoice.urls')),
    url(r'^messages/', include('howmuch.messages.urls')),
    url(r'^notifications/', include('howmuch.notifications.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^pays/', include('howmuch.pays.urls')),
    url(r'^prestige/', include('howmuch.prestige.urls')),
    url(r'^problems/', include('howmuch.problems.urls')),
    url(r'^profile/', include('howmuch.profile.urls')),
    url(r'^search/', include('howmuch.search.urls')),
    url(r'^tags/$', tags_json),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

howmuch/article/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


from howmuch.pictures.models import Picture
from howmuch.profile.models import Address
from howmuch.utils import get_timestamp
from howmuch.comments.models import Comment
from howmuch.tags.models import Tag
from howmuch.settings import URL_OFFICIAL_SITE



STATES_CHOICES = (

    ('nuevo' , 'Nuevo'),
    ('usado' , 'Usado'),
    ('indistinto', 'Indistinto')
)

QUANTITY_CHOICES = (
    (1,'1'),
    (2,'Entre 2 y 5'),
    (5,'Entre 5 y 10'),
    (10,'Mas de 10'),
    )

STATUS_ASSIGNMENT = (
    ('1', 'NOTIFICADO'), #Cuando la Asignacion es generada
    ('2', 'PAGADO'), #Cuando el comprador notifica el pago
    ('3', 'PRODUCTO ENVIADO'), # Cuando el vendedor notifica el Envio del producto, ya permite que los usuarios CRITIQUEN
    ('4','EN ESPERA DE CRITICA'), #Se activa en el momento en que cualquiera de los involucrados CRITICA la transaccion
    ('5', 'COMPLETADO'), #Cuando ya existe CRITICA tanto del comprador como del vendedor
    ('6', 'CANCELADO') #Cuando se cancela la transaccion
)

DAYS_CHOICES = (
    (1, 'UN DIA'),
    (5, 'CINCO'),
    (10, 'DIEZ'),
    (30, 'TREINTA'),
    )


class Article(models.Model):
    from howmuch.category.models import Category

    owner = models.ForeignKey(User, related_name = "owner by article")
    price = models.IntegerField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1024)
    quantity = models.IntegerField(choices=QUANTITY_CHOICES) 
    category = models.ForeignKey(Category)
    state = models.CharField(max_length=12, choices=STATES_CHOICES)
    tags = models.ManyToManyField(Tag)
    date = models.DateTimeField(auto_now_add=True)
    pictures = models.ManyToManyField(Picture)
    title_url = models.CharField(max_length=100, null=True, blank=True)
    comments = models.ManyToManyField(Comment, blank=True)
    followers = models.ManyToManyField(User, blank=True)
    is_active = models.BooleanField(default=True)


    def __unicode__(self):
        return u'Title: %s' % (self.title)

    #True si el item ya posee candidatos
    def has_candidates(self):
        if Offer.objects.filter(article = self).exists():
            return True
        return False


    #Regresa el numero de candidatos que han aplicado a este articulo
    def getNumber_candidates(self):
        return Offer.objects.filter(article = self).count()


    #True si el item ya posee asignacion
    def has_assignment(self):
        try:
            Assignment.objects.get(article = self)
        except Assignment.DoesNotExist:
            return False
        return True


    #True si el item ya ha finalizado
    def has_been_completed(self):
        try:
            assignment = Assignment.objects.get(article = self)
        except Assignment.DoesNotExist:
            return False
        if assignment.status == "4":
            return True
        return False


    #Regresa la URL de la primer imagen
    def get_first_picture_url(self):
        for p in self.pictures.all()[:1]:
            return p.get_url()


    #Regresa la URL del articulo
    def get_url(self):
        return '/article/%s/%s' % (self.pk, self.title_url)


    #Regresa una lista de Tags
    def get_list_tags(self):
        from howmuch.article.functions import tags_to_string
        return tags_to_string(self.tags.all())


    #Regresa hace que tiempo fue publicado el articulo        
    def get_timestamp(self):
        return get_timestamp(self.date)


    #return price range in format q to q
    def get_range_price(self):
        if self.price > 0 and self.price < 500:
            return '0to500'
        elif self.price > 500 and self.price < 1000:
            return '500to1000'
        elif self.price > 1000 and self.price < 5000:
            return '1000to5000'
        else:
            return 'gte5000'
        

class Offer(models.Model):
    owner = models.ForeignKey(User, related_name = "owner by Offer")
    article = models.ForeignKey(Article)
    date = models.DateTimeField(auto_now_add=True)
    #Precio contra oferta
    quantity = models.IntegerField(choices=QUANTITY_CHOICES) 
    cprice = models.IntegerField() 
    message = models.CharField(max_length=1024)
    pictures = models.ManyToManyField(Picture)

    def __unicode__(self):
        return u'owner: %s, item: %s' % (self.owner, self.article.title)

    #Regresa True si el articulo al que se hace referencia aun no tiene asignacion
    def is_open(self):
        try:
            Assignment.objects.get(article = self.article)
        except Assignment.DoesNotExist:
            return True
        return False

    def get_first_picture_url(self):
        for p in self.pictures.all()[:1]:
            return p.picture.url
            

    #Regresa hace que tiempo fue publicado el articulo        
    def get_timestamp(self):
        return get_timestamp(self.date)

    #Regresa la URL de la oferta, la podra ver unicamente el comprador del articulo
    def get_url(self):
        return URL_OFFICIAL_SITE + '/article/offer/view/%s' % (self.pk)


class Assignment(models.Model):
    owner = models.ForeignKey(User)
    article = models.OneToOneField(Article)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, default = 1)
    #offer = models.ForeignKey(Offer)

    def __unicode__(self):
        return u'Owner: %s and item: %s' % (self.owner, self.article)

    #True si el usuario dado es el vendedor del articulo
    def is_seller(self,user):
        if self.owner == user:
            return True
        else: 
            return False


    #True si el usuario dado es el comprador del articulo
    def is_buyer(self,user):
        if self.article.owner == user:
            return True
        else:
            return False


    #Regresa al comprador
    def get_buyer(self):
        return self.article.owner


    #Regresa al vendedor
    def get_seller(self):
        return self.owner


    #True si el usuario dado es comprador o vendedor
    def is_inside(self,user):
        if self.is_seller(user) or self.is_buyer(user):
            return True
        return False


    #True si en esta asignacion el comprador o vendedor ha criticado a su contraparte
    def has_been_critiqued_before(self):
        if self.status == "3":
            return True
        return False


    #True si la transaccion ha finalizado con exito
    def is_complete(self):
        if self.status == "4":
            return True
        return False

howmuch/category/models.py
from django.db import models

from howmuch.tags.models import Tag

class Category(models.Model):
	name = models.CharField(max_length=25)
	subname = models.CharField(max_length=35, blank=True, null=True )
	tags = models.ManyToManyField(Tag)

	def __unicode__(self):
		return u'%s' % (self.name)

howmuch/comments/models.py
from django.db import models
from django.contrib.auth.models import User

from howmuch.utils import get_timestamp

class Comment(models.Model):
	owner = models.ForeignKey(User, related_name="owner by comment")
	date = models.DateTimeField(auto_now_add=True)
	comment = models.CharField(max_length=255)

	def __unicode__(self):
		return u'%s' % (self.comment)

	def get_timestamp(self):
		return get_timestamp(self.date)

howmuch/config/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Notifications(models.Model):
    user = models.OneToOneField(User)
    new_offer = models.BooleanField(default=True)
    new_sale = models.BooleanField(default=True)
    new_message = models.BooleanField(default=True)
    confirm_pay = models.BooleanField(default=True)
    confirm_delivery = models.BooleanField(default=True)
    new_critique = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % (self.user)

    """
    Cuando se crea el nuevo usuario tambien se crea su configuracion de notificaciones
    """
    def create_user_config(sender, instance, created, **kwargs):
        if created:
            Notifications.objects.create(user=instance)

    post_save.connect(create_user_config, sender=User)

howmuch/pays/models.py
from django.db import models

# Create your models here.

howmuch/pictures/models.py
import os
import uuid

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from howmuch.pictures.thumbs import ImageWithThumbsField

def make_upload_path(instance, filename):
    file_root, file_ext = os.path.splitext(filename)
    dir_name = '{module}/{model}'.format(module=instance._meta.app_label, model=instance._meta.module_name)
    file_root = unicode(uuid.uuid4())
    name = os.path.join(settings.MEDIA_ROOT, 'images' ,dir_name, file_root + file_ext.lower())
    # Delete existing file to overwrite it later
    if instance.pk:
        while os.path.exists(name):
            os.remove(name)

    return os.path.join(dir_name, file_root + file_ext.lower())

class Picture(models.Model):
    picture = models.ImageField(upload_to=make_upload_path, blank=True)
    owner = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.picture.url

    def get_url(self):
        return str(self.picture.url).split("?")[0]

howmuch/tags/models.py
from django.db import models

class Tag(models.Model):
	name = models.CharField(max_length=50)
	usage = models.IntegerField(default=1)

	def __unicode__(self):
		return u'%s' % (self.name)

howmuch/article/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, Select

from howmuch.article.models import Article, Assignment

QUANTITY_CHOICES = (
    (1,'UNO'),
    (2,'ENTRE 2 y 5'),
    (5,'ENTRE 5 y 10'),
    (10,'MAS DE 10'),
    )

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        exclude = ('owner','tags','date','pictures','title_url', 'comments', 'followers', 'is_active')
        widgets = {
        'price' : TextInput(attrs = {'class' : 'text width-100'}),
        'title' : TextInput(attrs = {'class' : 'text width-100'}),
        'description' : Textarea(attrs = {'class' : 'width-100', 'style':'height:10em'}),
        'quantity' : Select(attrs = {'class' : 'width-100'}),
        'category' : Select(attrs = {'class' : 'width-100'}),
        'state' : Select(attrs = {'class' : 'width-100'}),
        }

class OfferForm(forms.Form):
    quantity = forms.ChoiceField(
        widget = forms.Select(attrs = {'class' : 'width-100'}),
        choices = QUANTITY_CHOICES)
    cprice = forms.IntegerField(
        widget = forms.TextInput(attrs = {'class' : 'text width-100'}))
    message = forms.CharField(
        widget = forms.Textarea(attrs = {'class' : 'width-100', 'style':'height:10em'}))
    picture1 = forms.ImageField(
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image1')"}))
    picture2 = forms.ImageField(required=False,
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image2')"}))
    picture3 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image3')"}))
    picture4 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image4')"}))
    picture5 = forms.ImageField(required=False, 
        widget = forms.ClearableFileInput(attrs = {'class' : 'input-file', 
            'onChange' : "readURL(this,'image5')"}))

class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        exclude = ('owner', 'article', 'date', 'status', )

howmuch/comments/forms.py
from django.forms import ModelForm

from howmuch.comments.models import Comment

class CommentForm(ModelForm):
	class Meta:
		model = Comment
		exclude = ('owner', 'date', )

howmuch/config/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext, ugettext_lazy as _


from howmuch.config.models import Notifications

class NotificationsConfigForm(ModelForm):
    class Meta:
        model = Notifications
        exclude = {'user',}


class EmailChangeForm(forms.Form):
	"""
	Formulario que le permite al usuario cambiar su correo electronico
	si coincide su password
	"""

	error_messages = {
		'incorrect_password' : _("The Password is incorrect")
	}

	new_email = forms.EmailField(label=_("new email"),
								widget=forms.TextInput(
									attrs={'class':'span12'}))
	password = forms.CharField(label=_("current password"),
								widget=forms.PasswordInput(
									attrs={'class':'span12'}))

	def __init__(self,user,*args,**kwargs):
		self.user = user
		super(EmailChangeForm, self).__init__(*args, **kwargs)

	def clean_password(self):
		if not self.user.check_password(self.cleaned_data['password']):
			raise forms.ValidationError(
				self.error_messages['incorrect_password'])


	def save(self, commit=True):
		self.user.check_password(self.cleaned_data['password'])
		if commit:
			self.user.email = self.cleaned_data['new_email']
			self.user.save()
		return self.user

howmuch/invoice/forms.py
from django import forms 
from django.forms import ModelForm

from howmuch.invoice.models import Pay

class PayForm(ModelForm):
	class Meta:
		model = Pay
		exclude = ('owner', 'date', 'invoice')

howmuch/messages/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from howmuch.messages.models import Message 

class MessageForm(ModelForm):
    class Meta:
        model = Message
        exclude = ('owner', 'date', 'conversation')
        widgets = {
            'message' : Textarea(attrs={'class' : 'span6', 'rows' : 2,'placeholder' : 'Escribe un mensaje aqui...'}),
        }

howmuch/pictures/forms.py
from django import forms
from django.forms import ModelForm

from howmuch.pictures.models import Picture

class PictureForm(ModelForm):
    class Meta:
        model = Picture
        exclude = ('owner' , 'date', )

howmuch/prestige/forms.py
from django import forms
from django.forms import ModelForm, Textarea, ClearableFileInput, TextInput, Select

from howmuch.prestige.models import ConfirmPay, ConfirmDelivery, Critique


class ConfirmPayForm(ModelForm):
    class Meta:
        model = ConfirmPay
        exclude = ('owner' , 'assignment', 'date',)
        widgets = {
        'amount' : TextInput(attrs={'class':'width-100'}),
        'message' : Textarea(attrs={'class':'width-100','style':'height:10em'}),
        'picture' : ClearableFileInput(attrs={'class':'text password width-100'}),
        }

class ConfirmDeliveryForm(ModelForm):
    class Meta:
        model = ConfirmDelivery
        exclude = ('owner', 'assignment', 'date',)
        widgets = {
        'message' : Textarea(attrs={'id':'confirm-delivery-file-upload-input','class':'width-100','style':'height:10em'}),
        'picture' : ClearableFileInput(attrs={'class':'text password width-100'}),
        }

class CritiqueForm(ModelForm):
    class Meta:
        model = Critique
        exclude = ('de', 'to', 'assignment', 'date',)
        widgets = {
        'critique' : Select(attrs={'class':'width-30'}),
        'message' : Textarea(attrs={'class':'width-100','style':'height:10em'}),
        }

howmuch/templates/prestige/critique.html
{% extends "3columns.html" %}

{% block title %}Critica a {{ to }}{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Enviar crítica</h1>
							<div class="description">
								Estás a punto de realizar una crítica sobre <a class="attention" href="/profile/{{ to }}">{{ to }}</a> con respecto al artículo <a class="attention" href="#">{{ assignment.article.title|title }}</a>.
							</div>
						</div>
					</div>
					
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if form.errors %}
						<div class="notification error border borders margin-bottom-1em text-align-left">
							<div class="strong">Error en la forma</div>
							<div class="notification-info">
								{{ form.errors }}
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area div-center-fix">
							<div class="text-align-left">
								
								<!-- PRINCIPAL INFO -->
								<div class="group border dashed">
									<div class="width-20 float-left">
										<div class="padding-1em text-align-center">
											<img class="width-100 padding-0_5em border" src="{{ assignment.article.get_first_picture_url }}" />
										</div>
									</div>
									<div class="width-70 float-right">
										<div class="padding-1em">
											<div class="item-title font-size-1_25em strong">
												{{ assignment.article.title|title }}
											</div>
											<div class="item-description">
												<span class="attention">&laquo;</span>
												<span>
													{{ assignment.article.description }}
												</span>
												<span class="attention">&raquo;</span>
											</div>
										</div>
									</div>
								</div>
								
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em text-align-center">
									<label for="" class="width-100 display-block margin-bottom-1em">
										<span class="font-size-1_25em ">Tu crítica para <a href="/profile/{{ to}}">{{ to}}</a></span>
									</label>
									{{ form.critique }}
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Sólo existen dos opciones, hay que ser extremistas para conocer realmente a los usuarios.
									</div>
									{% if form.critique.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.critique.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em text-align-center">
									<label for="" class="width-100 font-size-1_25em display-block margin-bottom-1em">Mensaje</label>

									{{ form.message }}

									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Deja algún mensaje explicando tu decisión en ésta crítica.
									</div>
									{% if form.message.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.message.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button green width-50" value="Confirmar" />
								</div>
								
							</div>
						</div>
					</form>
					<!-- FORM ENDS -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html" %}
{% endblock %}

howmuch/templates/prestige/deliveryConfirm.html
{% extends "3columns.html" %}

{% block title %}Confirmar Envio{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Confirmar Envío</h1>
							<div class="description">
								Estás a punto de confirmar el envío, llena por favor los siguientes datos.
							</div>
						</div>
					</div>
					
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if form.errors %}
						<div class="notification error border borders margin-bottom-1em text-align-left">
							<div class="strong">Error en la forma</div>
							<div class="notification-info">
								Verificar que hayas introducido los datos correctos en la forma.
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area div-center-fix">
							<div class="text-align-left">
								
								<!-- PRINCIPAL INFO -->
								<div class="group border dashed">
									<div class="width-20 float-left">
										<div class="padding-1em text-align-center">
											<img class="width-100 padding-0_5em border" src="{{ article.get_first_picture_url }}" />
										</div>
									</div>
									<div class="width-70 float-right">
										<div class="padding-1em">
											<div class="item-title font-size-1_25em strong">
												{{ article.title|title }}
											</div>
											<div class="item-description">
												<span class="attention">&laquo;</span>
												<span>
													{{ article.description|truncatechars:100 }}
												</span>
												<span class="attention">&raquo;</span>
											</div>
										</div>
									</div>
								</div>
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 font-size-1_25em display-block">Mensaje</label>
									{{ form.message }}
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Deja algún mensaje acerca de esta confirmación de envío.
									</div>
									{% if form.message.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.message.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">
										<span class="font-size-1_25em ">Subir fotografía</span>
										<span>(No es obligatorio)</span>
									</label>
									{{ form.picture }}
									<input id="confirm-delivery-file-upload-button" type="" class="button green" value="Seleccionar archivo" style="margin:0.5em 0px" />
									
									<script>
										$(window).on('load', function () {
											$('#id_picture').hide();
											$('#confirm-delivery-file-upload-button').on('click', function () {
												$('#id_picture').click();
											});
										});
									</script>
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Sube por ejemplo comprobantes de envío, fichas de envio, en formato .jpg
									</div>
									{% if form.picture.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.picture.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button green width-50" value="Enviar" />
								</div>
								
							</div>
						</div>
					</form>
					<!-- FORM ENDS -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html"%}
{% endblock %}

howmuch/templates/prestige/payConfirm.html
{% extends "3columns.html" %}

{% block title %}Confirmar Pago{% endblock %}

{% block section1 %}
	{% include "categories2.html" %}
{% endblock %}

{% block section2 %}
				<div class="content padding-1_5em">
					<div class="head">
						<div class="info margin-bottom-1em">
							<h1 class="font-size-1_5em">Confirmar Pago</h1>
							<div class="description">
								Estás a punto de confirmar el pago, llena por favor los siguientes datos.
							</div>
						</div>
					</div>
					
					<!-- FORM STARTS -->
					<form class="register-form border padding-1em text-align-center" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
						{% if form.errors %}
						<div class="notification error border borders margin-bottom-1em text-align-left">
							<div class="strong">Error en la forma</div>
							<div class="notification-info">
								Verificar que hayas introducido los datos correctos en la forma.
							</div>
						</div>
						{% endif %}
								
						<!-- FORM LOGIN STARTS -->
						<div class="login-form-area div-center-fix">
							<div class="text-align-left">
								
								<!-- PRINCIPAL INFO -->
								<div class="group border dashed">
									<div class="width-20 float-left">
										<div class="padding-1em text-align-center">
											<img class="width-100 padding-0_5em border" src="{{ article.get_first_picture_url }}" />
										</div>
									</div>
									<div class="width-70 float-right">
										<div class="padding-1em">
											<div class="item-title font-size-1_25em strong">
												{{ article.title|title }}
											</div>
											<div class="item-description">
												<span class="attention">&laquo;</span>
												<span>
													{{ article.description|truncatechars:100 }}
												</span>
												<span class="attention">&raquo;</span>
											</div>
										</div>
									</div>
								</div>
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 font-size-1_25em display-block">Cantidad</label>
									{{ form.amount }}
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Escribe la cantidad que has pagados.
									</div>
									{% if form.amount.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.amount.errors }}
									</div>
									{% endif %}
								</div>


								<div class="division margin-1em">
									<label for="" class="width-100 font-size-1_25em display-block">Mensaje</label>
									{{ form.message }}
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Deja algún mensaje acerca de esta confirmación de envío.
									</div>
									{% if form.message.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.message.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<!-- STARTS INPUT -->
								<div class="division margin-1em">
									<label for="" class="width-100 display-block">
										<span class="font-size-1_25em ">Subir fotografía</span>
										<span>(No es obligatorio)</span>
									</label>
									{{ form.picture }}
									<input id="confirm-delivery-file-upload-button" type="" class="button green" value="Seleccionar archivo" style="margin:0.5em 0px" />
									
									<script>
										$(window).on('load', function () {
											$('#id_picture').hide();
											$('#confirm-delivery-file-upload-button').on('click', function () {
												$('#id_picture').click();
											});
										});
									</script>
									
									<!-- ERROR -->
									<div class="slide-down font-size-0_9em margin-top-0_5em">
										Sube por ejemplo comprobantes de pago, fichas de pago, en formato .jpg
									</div>
									{% if form.picture.errors %}
									<div class="error slide-down color-red font-size-0_9em">
										{{ form.picture.errors }}
									</div>
									{% endif %}
								</div>
								<!-- ENDS INPUT -->
								
								<!-- DIVISION --><hr />
								
								<div class="division margin-1em text-align-center">
									<input type="submit" name="" class="button green width-50" value="Enviar" />
								</div>
								
							</div>
						</div>
					</form>
					<!-- FORM ENDS -->
				</div>
{% endblock %}

{% block section3 %}
	{% include "howtodo.html" %}
{% endblock %}

howmuch/templates/prestige/receivedConfirm.html
{% extends "3columns.html" %}

{% block title %}

{% endblock %}

{% block media %}

{% endblock %}

{% block section2 %}

{% endblock %}